[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''\/example.*\.pem$''',
    '''\/dummy-priv-key-gpg1423.asc''',
    '''\/dummy-priv-key.asc''',
  ]
  # Ignore based on any subset of the line
  regexes = [
    # Ignore lines containing pickles
    '''dummy''',
  ]
